# Generated by Django 4.2.11 on 2024-05-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_short', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shot_img/')),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.DeleteModel(
            name='MovieShort',
        ),
        migrations.AddField(
            model_name='movieshot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino_site.movie'),
        ),
    ]
